aliases:
    fleeks: cd /home/mike/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: ""
name: Fleek Configuration
packages:
    - helix
    - nerdfonts
    - neo
    - difftastic
    - starship
    - rogue
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: docker1
      os: linux
      username: mike
    - arch: x86_64
      hostname: thinkpad
      os: linux
      username: mike
unfree: true
users:
    - email: mcdent@gmail.com
      name: Mike Dent
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: mike
