aliases:
    fleeks: cd /home/mike/.local/share/fleek
bling: default
ejected: false
flakedir: .local/share/fleek
git:
<<<<<<< Updated upstream
    autocommit: true
=======
    autocommit: true 
>>>>>>> Stashed changes
    autopull: true 
    autopush: true 
    enabled: true 
name: Fleek Configuration
packages:
    - helix
    - nerdfonts
    - neo
    - difftastic
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      hostname: docker1
      os: linux
      username: mike
    - arch: x86_64
      hostname: thinkpad
      os: linux
      username: mike
unfree: true
